const DATA_PATH = 'data/generated';
const MONTHS = [1,2,3,4,5,6,7,8,9,10,11,12];
const CITIES = [
  ['it-rome','Rome','Rom','Roma'],['pt-lisbon','Lisbon','Lissabon','Lisboa'],['gr-athens','Athens','Athen','Atenas'],['es-barcelona','Barcelona','Barcelona','Barcelona'],['es-madrid','Madrid','Madrid','Madrid'],['fr-paris','Paris','Paris','París'],['gb-london','London','London','Londres'],['nl-amsterdam','Amsterdam','Amsterdam','Ámsterdam'],['de-berlin','Berlin','Berlin','Berlín'],['at-vienna','Vienna','Wien','Viena'],['cz-prague','Prague','Prag','Praga'],['hu-budapest','Budapest','Budapest','Budapest'],['dk-copenhagen','Copenhagen','Kopenhagen','Copenhague'],['se-stockholm','Stockholm','Stockholm','Estocolmo'],['it-milan','Milan','Mailand','Milán'],['it-naples','Naples','Neapel','Nápoles'],['hr-dubrovnik','Dubrovnik','Dubrovnik','Dubrovnik'],['tr-istanbul','Istanbul','Istanbul','Estambul'],['es-valencia','Valencia','Valencia','Valencia'],['pt-porto','Porto','Porto','Oporto']
];
const WALK_WEIGHTS = { light:{day:25,night:35,humidity:15,rain:15,variability:10}, normal:{day:32,night:32,humidity:16,rain:12,variability:8}, high:{day:40,night:28,humidity:17,rain:8,variability:7} };
const TOLERANCE = { low:1.25, medium:1, high:.75 };
let climate = [];
let mode = 'destination';

const COPY = {
  en:{kicker:'Plan your way',title:'How are you planning your trip?',intro:'Start with what you already know. wohlfuehlreisen turns it into a personal comfort check.',modes:[['destination','📍','I already know where I want to go','Check whether a destination and month fit me.'],['month','🗓️','I know when I want to travel','Find cities that fit me in a specific month.'],['surprise','✨','Surprise me','Show me places where I am likely to feel good.']],destination:'Destination',month:'Travel month',action:'Check my comfort',score:'wohlfuehlreisen match',fit:'Why it fits you',great:'Very strong fit for your preferences.',good:'Good fit, with only small tradeoffs.',mixed:'Reasonable fit, but there are noticeable compromises.',weak:'This month is likely outside your comfort zone.',day:'Daytime heat',night:'Night temperature',humidity:'Humidity',rain:'Rain',best:'Better timing',better:'For this destination, {month} scores {score}/100 for you.',rankTitle:'Best matches for {month}',rankHint:'Ranked using your current comfort settings.',choose:'Choose a destination',pick:'Choose a month'},
  de:{kicker:'Plane auf deine Art',title:'Wie planst du deine Reise?',intro:'Starte mit dem, was du schon weißt. wohlfuehlreisen macht daraus deinen persönlichen Klima-Check.',modes:[['destination','📍','Ich weiß schon, wohin ich will','Prüfe, ob Reiseziel und Monat zu mir passen.'],['month','🗓️','Ich weiß, wann ich reisen will','Finde Städte, die in meinem Reisemonat zu mir passen.'],['surprise','✨','Überrasche mich','Zeig mir Orte, an denen ich mich wahrscheinlich wohlfühle.']],destination:'Reiseziel',month:'Reisemonat',action:'Mein Klima prüfen',score:'wohlfuehlreisen Match',fit:'Warum es zu dir passt',great:'Sehr starke Übereinstimmung mit deinen Vorlieben.',good:'Gute Übereinstimmung mit nur kleinen Kompromissen.',mixed:'Solide Option, aber mit spürbaren Kompromissen.',weak:'Dieser Monat liegt wahrscheinlich außerhalb deiner Komfortzone.',day:'Tageshitze',night:'Nachttemperatur',humidity:'Luftfeuchtigkeit',rain:'Regen',best:'Besserer Zeitraum',better:'Für dieses Reiseziel erreicht {month} bei dir {score}/100.',rankTitle:'Beste Treffer für {month}',rankHint:'Bewertet mit deinen aktuellen Komfort-Einstellungen.',choose:'Reiseziel wählen',pick:'Monat wählen'},
  es:{kicker:'Planifica a tu manera',title:'¿Cómo estás planificando tu viaje?',intro:'Empieza con lo que ya sabes. wohlfuehlreisen lo convierte en una comprobación personal de confort.',modes:[['destination','📍','Ya sé adónde quiero ir','Comprueba si un destino y un mes encajan conmigo.'],['month','🗓️','Sé cuándo quiero viajar','Encuentra ciudades que encajen conmigo en un mes concreto.'],['surprise','✨','Sorpréndeme','Muéstrame lugares donde probablemente me sienta bien.']],destination:'Destino',month:'Mes de viaje',action:'Comprobar mi confort',score:'Compatibilidad wohlfuehlreisen',fit:'Por qué encaja contigo',great:'Encaje muy fuerte con tus preferencias.',good:'Buen encaje, con pocos compromisos.',mixed:'Encaje razonable, aunque con compromisos visibles.',weak:'Este mes probablemente queda fuera de tu zona de confort.',day:'Calor diurno',night:'Temperatura nocturna',humidity:'Humedad',rain:'Lluvia',best:'Mejor momento',better:'Para este destino, {month} obtiene {score}/100 para ti.',rankTitle:'Mejores opciones para {month}',rankHint:'Clasificadas con tus preferencias actuales.',choose:'Elige un destino',pick:'Elige un mes'}
};

function lang(){ return ['en','de','es'].includes(document.documentElement.lang) ? document.documentElement.lang : 'en'; }
function t(){ return COPY[lang()]; }
function cityName(id){ const c=CITIES.find(x=>x[0]===id); if(!c)return id; return c[lang()==='de'?2:lang()==='es'?3:1]; }
function monthName(m){ return new Intl.DateTimeFormat(lang()==='de'?'de-DE':lang()==='es'?'es-ES':'en-US',{month:'long'}).format(new Date(2024,m-1,1)); }
function clamp(v){ return Math.max(0,Math.min(100,v)); }
function prefs(){ return {day:Number(document.querySelector('#maxDay')?.value||28),night:Number(document.querySelector('#maxNight')?.value||21),humidity:document.querySelector('input[name="humidity"]:checked')?.value||'medium',rain:document.querySelector('input[name="rain"]:checked')?.value||'medium',walk:document.querySelector('input[name="walk"]:checked')?.value||'normal'}; }
function score(item,p){ const dayCold=clamp(Math.max(0,18-item.dayApparentC.p75)*8+Math.max(0,13-item.dayApparentC.p75)*4); const nightCold=clamp(Math.max(0,10-item.nightMinC.p75)*10+Math.max(0,6-item.nightMinC.p75)*6); const day=clamp(Math.max(0,item.dayApparentC.p75-p.day)*12+Math.max(0,item.dayApparentC.p90-p.day)*4+dayCold); const night=clamp(Math.max(0,item.nightMinC.p75-p.night)*16+Math.max(0,item.nightMinC.p90-p.night)*5+nightCold); const penalties={day,night,humidity:clamp(item.humidHoursPct*TOLERANCE[p.humidity]),rain:clamp(item.wetDaysPct*TOLERANCE[p.rain]),variability:clamp(item.variability*100)}; const w=WALK_WEIGHTS[p.walk]; const total=Object.keys(w).reduce((s,k)=>s+penalties[k]*w[k],0); return Math.max(0,Math.min(100,Math.round(100-total/100))); }
function verdict(s){ const x=t(); return s>=85?x.great:s>=72?x.good:s>=58?x.mixed:x.weak; }
function metricState(kind,item,p){ if(kind==='day') return item.dayApparentC.p75<=p.day?'good':'warn'; if(kind==='night') return item.nightMinC.p75<=p.night?'good':'warn'; if(kind==='humidity') return item.humidHoursPct<=(p.humidity==='low'?20:p.humidity==='medium'?35:50)?'good':'warn'; return item.wetDaysPct<=(p.rain==='low'?20:p.rain==='medium'?35:50)?'good':'warn'; }
function metric(label,value,state){ return `<div class="personal-metric metric-${state}"><b>${state==='good'?'✓':'⚠'} ${label}</b><span>${value}</span></div>`; }

function mount(){ const quick=document.querySelector('.quick-finder'); if(!quick||document.querySelector('#tripJourney'))return; const s=document.createElement('section'); s.id='tripJourney'; s.className='trip-journey'; quick.before(s); renderJourney(); ['input','change'].forEach(evt=>document.addEventListener(evt,e=>{ if(e.target.matches('#maxDay,#maxNight,input[name="humidity"],input[name="rain"],input[name="walk"]')) updatePersonalResult(); })); document.querySelectorAll('.type-card').forEach(b=>b.addEventListener('click',()=>setTimeout(updatePersonalResult,0))); document.querySelectorAll('.lang-btn').forEach(b=>b.addEventListener('click',()=>setTimeout(()=>{renderJourney();updatePersonalResult();},0))); }

function renderJourney(){ const x=t(), root=document.querySelector('#tripJourney'); if(!root)return; root.innerHTML=`<div class="section-kicker">${x.kicker}</div><h2>${x.title}</h2><p class="journey-intro">${x.intro}</p><div class="journey-modes">${x.modes.map(([id,icon,title,sub])=>`<button type="button" class="journey-mode ${mode===id?'active':''}" data-journey-mode="${id}"><span>${icon}</span><strong>${title}</strong><small>${sub}</small></button>`).join('')}</div><div class="journey-controls" id="journeyControls"></div>`; root.querySelectorAll('[data-journey-mode]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.journeyMode;renderJourney();applyMode();})); renderControls(); applyMode(); }
function renderControls(){ const x=t(), c=document.querySelector('#journeyControls'); if(!c)return; if(mode==='surprise'){c.innerHTML='';return;} const cityOptions=CITIES.map(([id])=>`<option value="${id}">${cityName(id)}</option>`).join(''); const monthOptions=MONTHS.map(m=>`<option value="${m}">${monthName(m)}</option>`).join(''); if(mode==='destination') c.innerHTML=`<div class="journey-field"><label for="journeyCity">${x.destination}</label><select id="journeyCity">${cityOptions}</select></div><div class="journey-field"><label for="journeyMonth">${x.month}</label><select id="journeyMonth">${monthOptions}</select></div><button class="journey-action" id="journeyGo" type="button">${x.action}</button>`; else c.innerHTML=`<div class="journey-field"><label for="journeyMonth">${x.month}</label><select id="journeyMonth">${monthOptions}</select></div><button class="journey-action" id="journeyGo" type="button">${x.action}</button>`; document.querySelector('#journeyGo')?.addEventListener('click',()=>{updatePersonalResult(true);document.querySelector('#results')?.scrollIntoView({behavior:'smooth',block:'start'});}); }

function applyMode(){ const original=document.querySelector('#visualSummary'); const resultsTitle=document.querySelector('#results-title'); const resultsSub=document.querySelector('#resultsSubtitle'); document.querySelector('#personalJourneyResult')?.remove(); if(mode==='surprise'){ original?.classList.remove('journey-hidden'); return; } original?.classList.add('journey-hidden'); if(resultsTitle) resultsTitle.textContent=mode==='destination'?t().fit:t().rankTitle.replace('{month}',monthName(Number(document.querySelector('#journeyMonth')?.value||1))); if(resultsSub&&mode==='month')resultsSub.textContent=t().rankHint; }

function updatePersonalResult(force=false){ if(mode==='surprise'||!climate.length)return; const city=document.querySelector('#journeyCity')?.value; const month=Number(document.querySelector('#journeyMonth')?.value||1); if(!force&&!document.querySelector('#personalJourneyResult'))return; if(mode==='destination') renderDestination(city,month); else renderMonth(month); }
function resultHost(){ const host=document.querySelector('#personalJourneyResult')||document.createElement('div'); host.id='personalJourneyResult'; if(!host.isConnected) document.querySelector('#visualSummary')?.before(host); return host; }
function renderDestination(city,month){ const x=t(), p=prefs(), item=climate.find(i=>i.locationId===city&&Number(i.month)===month); if(!item)return; const s=score(item,p); const all=climate.filter(i=>i.locationId===city).map(i=>({item:i,score:score(i,p)})).sort((a,b)=>b.score-a.score); const best=all[0]; const alt=best&&Number(best.item.month)!==month?`<p class="personal-alternative"><strong>${x.best}:</strong> ${x.better.replace('{month}',monthName(Number(best.item.month))).replace('{score}',best.score)}</p>`:''; resultHost().innerHTML=`<article class="personal-result"><div class="personal-result-head"><div><p class="personal-result-eyebrow">${x.fit}</p><h3>${cityName(city)} · ${monthName(month)}</h3><p class="personal-result-sub">${verdict(s)}</p></div><div class="personal-score"><strong>${s}/100</strong><small>${x.score}</small></div></div><div class="personal-verdict">${verdict(s)}</div><div class="personal-breakdown">${metric(x.day,`${item.dayApparentC.p75}°C · limit ${p.day}°C`,metricState('day',item,p))}${metric(x.night,`${item.nightMinC.p75}°C · limit ${p.night}°C`,metricState('night',item,p))}${metric(x.humidity,`${item.humidHoursPct}%`,metricState('humidity',item,p))}${metric(x.rain,`${item.wetDaysPct}% wet days`,metricState('rain',item,p))}</div>${alt}</article>`; }
function renderMonth(month){ const x=t(), p=prefs(); const ranked=CITIES.map(([id])=>{const item=climate.find(i=>i.locationId===id&&Number(i.month)===month);return item?{id,item,score:score(item,p)}:null;}).filter(Boolean).sort((a,b)=>b.score-a.score).slice(0,5); const cards=ranked.map((r,i)=>`<article class="city-match ${i===0?'top-match':''}"><span class="city-rank">${i+1}</span><span class="city-score">${r.score}/100</span><div class="city-match-copy"><h3>${cityName(r.id)}</h3><p class="gentle-description">${verdict(r.score)}</p><details class="city-more"><summary>${x.fit}</summary><ul><li>${x.day}: ${r.item.dayApparentC.p75}°C</li><li>${x.night}: ${r.item.nightMinC.p75}°C</li><li>${x.humidity}: ${r.item.humidHoursPct}%</li><li>${x.rain}: ${r.item.wetDaysPct}%</li></ul></details></div></article>`).join(''); resultHost().innerHTML=`<div class="month-ranked">${cards}</div>`; const title=document.querySelector('#results-title'); if(title)title.textContent=x.rankTitle.replace('{month}',monthName(month)); const sub=document.querySelector('#resultsSubtitle');if(sub)sub.textContent=x.rankHint; }

async function load(){ try{const r=await fetch(`${DATA_PATH}/bundle.json`); if(r.ok){const b=await r.json(); climate=Object.values(b.cities).flatMap(city=>Object.values(city)); return;}}catch{} const req=CITIES.flatMap(([id])=>MONTHS.map(m=>fetch(`${DATA_PATH}/${id}-${String(m).padStart(2,'0')}.json`).then(r=>r.ok?r.json():null).catch(()=>null))); climate=(await Promise.all(req)).filter(Boolean); }

mount(); load().then(()=>updatePersonalResult());
